name: Main workflow
on: issues
jobs:
  main_first:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{github.action}}
      - run: echo ${{github.event.action}}
      - run: echo $GITHUB_ACTION
