name: Main workflow
on: workflow_dispatch
jobs:
  main_first:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Tehdään jotan mainissa"
  main_second:
    needs: main_first
    uses: './.github/workflows/test.yml'
