name: Main workflow
on: issues
jobs:
  main_first:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Eka ${{github.event_name}}"
          echo "Toka ${{github.event.action}}"
          echo "Kolmas $GITHUB_EVENT_NAME"
      - name: Testi
        if: ${{github.event_name == 'issue'}}
        run: echo "Onnistui"
