name: Testing
on: workflow_dispatch
jobs:
  first:
    runs-on: ubuntu-latest
    outputs:
        myval: ${{steps.muikula.outputs.test}}
    steps:
      - id: muikula
        run: echo "test=kokeilu" >> $GITHUB_OUTPUT
  second:
    runs-on: ubuntu-latest
    needs: first
    env:
      MUUTTUJA: ${{needs.first.outputs.myval}}
    steps:
      - run: echo "$MUUTTUJA ...."
    
