name: Job order
on: workflow_dispatch

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "First job"
          echo "First job"
          echo "First job"
          echo "First job"
          exit 1
          echo "First job"
  second_job:
    if: always()
    needs: first_job
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo  "Second job"
          echo  "Second job"
          echo  "Second job"
          echo  "Second job"
          echo  "Second job"
          echo  "Second job"
          
