name: Testing
on: workflow_dispatch
jobs:
  first:
    runs-on: ubuntu-latest
    outputs:
        myval: ${{steps.muikula.outputs.test}}
    steps:
      - name: muikula
        run: echo "test=kokeilu" >> $GITHUB_OUTPUT
