name: Uusi
on: workflow_dispatch
jobs:
  testi:
    env:
      TEMP: ${{toJson(github.event)}}
    runs-on: ubuntu-latest
    container: python:3.11.17-alpine3.24
    steps:
      - run: |
          python --version
      
