name: Uusi
on: 
  release:
    types: published
jobs:
  testi:
    env:
      TEMP: ${{toJson(github.event)}}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "----------------------------------"
          echo "$TEMP"
          echo "----------------------------------"
      
